hoosk: Fix

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
 
-echo 'Linter:' && io.elementary.vala-lint -d . -c vala-lint.conf
-echo 'Empty lines:' && python3 ${workspaceFolder}/vala-checkers/empty_lines_checker.py .
-echo 'Indentation:' && python3 ${workspaceFolder}/vala-checkers/indentation_checker.py .
+set -e
+
+echo 'Linter failed'
+io.elementary.vala-lint -d . -c vala-lint.conf
+
+echo 'Empty lines check failed'
+python3 vala-checkers/empty_lines_checker.py .
+
+echo 'Indentation check failed'
+python3 vala-checkers/indentation_checker.py .
+
 blueprint-compiler format -s 2 data/ui/*.blp
